### ISSUE TITLE
user token过期的策略是什么？能否自动化获取user token

### ISSUE THREAD

**Issue by Lseven-zzw** [qjc1024join/midjourney-bot-api#1]

**Comment by qjc1024join** [comment]
这个没有过期策略，我目前没有碰到token过期，貌似一个多月了，还是正常使用的，如果出现过期的情况您在反馈，到时候抓取一下登录接口等问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qjc1024join/midjourney-bot-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月12日(星期五) 上午10:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[qjc1024join/midjourney-bot-api] user token过期的策略是什么？能否自动化获取user token (Issue #1)

**Comment by Lseven-zzw** [comment]
thanks
